Fix new mypy error
Fix the following error detected with the current upper constraints.

oslo_cache/tests/unit/test_cache_basics.py:1132: error:
Unused "type: ignore" comment  [unused-ignore]

Change-Id: Ibce46506ecfe502ede5697c3ecbe0f849e95508d
Signed-off-by: Takashi Kajinami <kajinamit@oss.nttdata.com>