Fix mypy errors
Fix the following errors detected.

oslo_cache/_memcache_pool.py:280:16: error: Incompatible return value
type (got "type[_MemcacheClient]", expected "_MemcacheClient")
[return-value]

oslo_cache/_bmemcache_pool.py:91:16: error: Incompatible return value
type (got "type[_BMemcacheClient]", expected "_BMemcacheClient")
[return-value]

Change-Id: I5809e3e0523c53bd916d6f1eeb93b62110af0460
Signed-off-by: Takashi Kajinami <kajinamit@oss.nttdata.com>
(cherry picked from commit a14d55b2212f404014ce16b3fad605de3dde81c0)